[workspace]
members = [
    "language/rust",
    "language/references",
    "projects/minigrep", 
    "projects/hello-world", 
    "projects/greeting", 
    "projects/input-sum", 
    "projects/input-cal",  
    "dsa/bubble_sort",
]
resolver = "2"

[workspace.dependencies]
rayon = "1.11.0"