[workspace]
members = [
    "code", 
    "projects/minigrep", 
    "projects/hello-world", 
    "projects/greeting", 
    "projects/input-sum", 
    "projects/input-cal",  "dsa/bubble_sort",
]
resolver = "2"
