[package]
name = "references"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.2"
signal-hook = { version = "0.3.18", features = ["iterator"]}
rayon = {workspace = true}